# Global variables
namespace: cassis
stacker_execution_profile: &stacker_execution_profile stacker_execution
stacker_bucket: ""  # not using S3 buckets to store CloudFormation templates

stacks:

  - name: cassis-s3
    profile: *stacker_execution_profile
    template_path: templates/s3-bucket-template.yaml
    variables:
      BucketName: $(BucketName)

  - name: cassis-vpc
    profile: *stacker_execution_profile
    template_path: templates/vpc.yaml
    variables:
      S3Arn: ${output cassis-s3::S3BucketArn}
      EnvironmentName: ${EnvironmentName}
      VpcCIDR: ${VpcCIDR}
      PrivateSubnet1CIDR: ${PrivateSubnet1CIDR}
      PrivateSubnet2CIDR: ${PrivateSubnet2CIDR}
